/* Production account setup and release identity. */
(function(root){'use strict';
const RELEASE='5.3-production.1';
function createSetup({Vue,API}){return{setup(){
 const s=Vue.reactive({token:'',password:'',confirm:'',busy:false,error:'',done:false,show:false});
 let previousFocus=null,previousOverflow='';
 Vue.watch(()=>!!(s.token||s.done),open=>{if(open){previousFocus=document.activeElement;previousOverflow=document.body.style.overflow;document.body.style.overflow='hidden'}else{document.body.style.overflow=previousOverflow;previousFocus?.focus?.()}});
 const trap=e=>{if(!(s.token||s.done)||e.key!=='Tab')return;const dialog=document.querySelector('.ac-personal-setup');const nodes=Array.from(dialog?.querySelectorAll('input,button,[tabindex="0"]')||[]).filter(n=>!n.disabled);if(!nodes.length)return;const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&(document.activeElement===first||!dialog.contains(document.activeElement))){e.preventDefault();last.focus()}else if(!e.shiftKey&&(document.activeElement===last||!dialog.contains(document.activeElement))){e.preventDefault();first.focus()}};
 Vue.onMounted(()=>document.addEventListener('keydown',trap));Vue.onUnmounted(()=>{document.removeEventListener('keydown',trap);document.body.style.overflow=previousOverflow});
 Vue.watch(()=>s.done,done=>{if(done)Vue.nextTick(()=>document.querySelector('.ac-personal-setup button')?.focus())});
 const begin=e=>{Object.assign(s,{token:e.detail.token,password:'',confirm:'',busy:false,error:'',done:false,show:false});Vue.nextTick(()=>document.getElementById('personal-password')?.focus())};
 Vue.onMounted(()=>root.addEventListener('neumdesk:password-setup',begin));Vue.onUnmounted(()=>{root.removeEventListener('neumdesk:password-setup',begin);s.token='';s.password='';s.confirm=''});
 const cancel=()=>{s.token='';s.password='';s.confirm='';s.error=''};
 async function submit(){if(s.busy)return;if(s.password!==s.confirm){s.error='The two passwords do not match.';return}if(s.password.length<15||new TextEncoder().encode(s.password).length>72){s.error='Use at least 15 characters and at most 72 UTF-8 bytes.';return}s.busy=true;s.error='';try{await API.request('/api/auth/complete-password-setup',{method:'POST',body:{setup_token:s.token,new_password:s.password},timeoutMs:15000});s.done=true;s.token='';s.password='';s.confirm='';API.clearAuthStorage();API.clearCache()}catch(e){s.error=e.message}finally{s.busy=false}}
 return{s,submit,cancel,finish:()=>root.location.reload()};
},template:`<div v-if="s.token||s.done" class="ac-setup ac-personal-setup"><section class="ac-setup-card" role="dialog" aria-modal="true" aria-labelledby="personal-title"><p class="ac-eyebrow">Your account · Your password</p><h1 id="personal-title">{{s.done?'You’re ready to sign in.':'Make this account yours.'}}</h1><template v-if="s.done"><p>Your personal password is saved. The temporary credentials no longer work.</p><button class="btn btn-primary" @click="finish">Continue to sign in</button></template><form v-else @submit.prevent="submit"><p>Your administrator provided temporary access. Choose a personal password to enter the workspace.</p><p v-if="s.error" role="alert" class="ac-alert">{{s.error}}</p><label for="personal-password">Personal password</label><input id="personal-password" :type="s.show?'text':'password'" v-model="s.password" autocomplete="new-password" required minlength="15" maxlength="72"><label for="personal-confirm">Confirm personal password</label><input id="personal-confirm" :type="s.show?'text':'password'" v-model="s.confirm" autocomplete="new-password" required minlength="15" maxlength="72"><label class="ac-show-password"><input type="checkbox" v-model="s.show">Show passwords</label><p class="ac-meta">Use a memorable passphrase of at least 15 characters. Setup access expires after 10 minutes.</p><div class="ac-actions"><button class="btn btn-primary" :disabled="s.busy">{{s.busy?'Saving…':'Save personal password'}}</button><button type="button" class="btn btn-secondary" :disabled="s.busy" @click="cancel">Back</button></div></form></section></div>`}}
function createRelease({Vue,API}){return {setup(){const state=Vue.reactive({status:'checking',backend:'',error:''});async function check(){state.status='checking';try{const r=await API.request('/api/release',{skipCache:true,timeoutMs:8000});state.backend=r.id;state.status=r.id===RELEASE?'matched':'mismatch';state.error=''}catch{state.status='unavailable';state.error='Could not verify the backend release.'}}Vue.onMounted(check);return{state,check,release:RELEASE}},template:`<aside class="release53" :data-state="state.status" aria-label="Application release"><span>{{release}}</span><span v-if="state.status==='matched'">Frontend &amp; backend matched</span><template v-else><span role="status">{{state.status==='mismatch'?'Versions differ. Refresh or deploy the matching pair.':state.status==='checking'?'Checking backend…':state.error}}</span><button @click="check">Check again</button></template></aside>`}}
root.NeumProduction={RELEASE,createSetup,createRelease};
})(window);
