/* Read-only operational review. Uses only records already authorized by the API. */
(function(root){'use strict';
const day=v=>String(v||'').slice(0,10);
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
function findings({rotations=[],absences=[],oncall=[],date=today()}){
 const out=[];
 for(const r of rotations){
  if(r.rotation_status==='terminated_early'&&!r.actual_end_date)out.push({id:'date:'+r.id,kind:'Dates',view:'resident_rotations',title:'Actual rotation end is missing',detail:`Planned ${day(r.start_date)} to ${day(r.end_date)}. Review the actual end date; do not infer it from the planned end.`,subject:r.resident_id});
  if(['active','scheduled','extended'].includes(r.rotation_status)&&day(r.end_date)&&day(r.end_date)<date)out.push({id:'close:'+r.id,kind:'Lifecycle',view:'resident_rotations',title:'Rotation passed its planned end',detail:`Planned end ${day(r.end_date)}. Confirm completion or record an extension.`,subject:r.resident_id});
 }
 const active=absences.filter(a=>!['cancelled','returned_to_duty','completed'].includes(a.current_status));
 for(const shift of oncall.filter(s=>day(s.duty_date)===date))for(const id of new Set([shift.primary_physician_id,shift.resident_physician_id,shift.backup_physician_id].filter(Boolean))){
  const leave=active.find(a=>(a.staff_member_id===id||a.medical_staff_id===id||a.staff_id===id)&&day(a.start_date)<=date&&day(a.actual_return_date||a.end_date)>=date);
  if(leave)out.push({id:'coverage:'+shift.id+':'+id,kind:'Coverage',view:'oncall',title:'On-call assignment overlaps recorded leave',detail:`${date} · leave ${day(leave.start_date)} to ${day(leave.actual_return_date||leave.end_date)}. Review coverage before making a change.`,subject:id});
 }
 return out;
}
function profileChecks(p={}){return [{label:'Professional biography',ok:!!String(p.public_bio||'').trim()},{label:'Profile photograph',ok:!!p.public_photo_url},{label:'Professional email',ok:!!p.professional_email},{label:'ORCID',ok:!!p.orcid_id}];}
function publicationChecks(p={}){return [{label:'Title',ok:!!String(p.title||'').trim()},{label:'Public visibility selected',ok:p.is_public===true},{label:'Published status',ok:p.status==='published'},{label:'DOI (for publications)',ok:p.post_type!=='publication'||!!p.doi}];}
function createReview({Vue}){return{props:{rotations:Array,absences:Array,oncall:Array,staff:Array,can:Function},emits:['navigate'],setup(p){const date=Vue.ref(today());const timer=setInterval(()=>{date.value=today()},60000);Vue.onUnmounted(()=>clearInterval(timer));const rows=Vue.computed(()=>findings({rotations:p.can('resident_rotations','read')?p.rotations:[],absences:p.can('staff_absence','read')?p.absences:[],oncall:p.can('oncall_schedule','read')?p.oncall:[],date:date.value}));const expanded=Vue.ref(false);return{date,rows,expanded,name:id=>p.staff?.find(s=>s.id===id)?.full_name||'Staff record'}},template:`<section class="review53" aria-labelledby="review53-title"><header><div><p class="ac-eyebrow">Operational review · {{date}}</p><h2 id="review53-title">What needs a closer look</h2><p>Advisory checks on the records you can access. Review and confirm changes in the relevant module.</p></div><button class="btn btn-secondary" @click="expanded=!expanded" :aria-expanded="expanded">{{expanded?'Hide details':'Review '+rows.length+' items'}}</button></header><p v-if="!rows.length" class="review53-clear">No issues found by these date and leave-overlap checks. Other module warnings may still apply.</p><div v-if="expanded&&rows.length" class="review53-list"><article v-for="r in rows" :key="r.id"><span class="ac-chip">{{r.kind}} · Review</span><h3>{{r.title}}</h3><strong>{{name(r.subject)}}</strong><p>{{r.detail}}</p><button class="ac-text-button" @click="$emit('navigate',r.view)">Open {{r.view==='oncall'?'on-call':'rotations'}} →</button></article></div></section>`}}
function createReadiness({Vue}){return {props:{record:Object,kind:String},setup(p){return{checks:Vue.computed(()=>p.kind==='profile'?profileChecks(p.record):publicationChecks(p.record))}},template:`<details class="readiness53"><summary>{{kind==='profile'?'Professional profile checklist':'Public publishing checklist'}}</summary><p>{{kind==='profile'?'These checks help you complete the profile. Public visibility is controlled separately.':'Review the record and its public preview before publishing. This checklist does not publish or certify the content.'}}</p><ul><li v-for="item in checks" :key="item.label"><span :class="{'is-ready':item.ok}">{{item.ok?'Present':'Review'}}</span>{{item.label}}</li></ul></details>`}}
const api={findings,profileChecks,publicationChecks,createReview,createReadiness};root.NeumReview53=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
