const fs=require('fs'), vm=require('vm'), assert=require('assert');
const html=fs.readFileSync('index.html','utf8');
const app=fs.readFileSync('app.js','utf8');
const activity=fs.readFileSync('activity45.js','utf8');
const css=fs.readFileSync('activity45-ui.css','utf8');
const dept=fs.readFileSync('DepartmentOS_Architecture.md','utf8');
const grounded=fs.readFileSync('GROUNDED-ARCHITECTURE.md','utf8');
const checks=[]; const test=(n,fn)=>checks.push([n,fn]);
test('V46.13-or-later cache markers',()=>{assert(html.includes('activity45-ui.css?v=46.13')||html.includes('activity45-ui.css?v=46.14'));assert(html.includes('activity45.js?v=46.13')||html.includes('activity45.js?v=46.14'));assert(html.includes('app.js?v=46.13-portfolio-intelligence')||(html.includes('app.js?v=46.14-personal-activity-workspace') || html.includes('app.js?v=46.14-grounded-presentation-convergence')))});
test('personal activity keeps structured model in reactive state',()=>assert(/model:null,summary:null,view:'overview'/.test(app)));
test('build attaches structured summary',()=>{assert(activity.includes('model.summary=summarize(model)'));assert(activity.includes('function summarize(m)'))});
test('summary preserves duties rotations and portfolio dimensions',()=>['oncall:','rotations:','residentRotations:','supervisedRotations:','studies:','projects:','programmes:','sourceCoverage:'].forEach(x=>assert(activity.includes(x))));
test('interactive views exist before document',()=>['Overview','Timeline','Portfolio','Document'].forEach(x=>assert(html.includes(`label:'${x}'`))));
test('document remains same-snapshot output',()=>{assert(html.includes('Generated from the same verified snapshot')||html.includes('Generated from exactly the same verified snapshot')||html.includes('Generated from the same permission-scoped snapshot'));assert(app.includes('activity45.html=Activity45.render(model)'))});
test('source coverage is first-class UI',()=>{assert(html.includes('source coverage')||html.includes('Evidence coverage')||html.includes('Retrieval evidence')||html.includes('included sources retrieved'));assert(html.includes('activity45.model.sources'));assert(html.includes('Evidence & provenance'))});
test('missing data truthfulness is explicit',()=>{assert(html.includes('never interpreted as zero activity')||html.includes('Missing data is never interpreted as no activity'));assert(html.includes('does not establish availability'))});
test('privacy boundary remains explicit',()=>assert(html.includes('Private notes, contact details and leave reasons are excluded')||html.includes('Leave reasons, contact details and private staff notes are excluded')));
test('portfolio uses explicit model relationships',()=>{assert(html.includes('activity45.model.studies'));assert(html.includes('activity45.model.projects'));assert(html.includes('activity45.model.lines'))});
test('timeline uses structured events',()=>assert(html.includes('activity45.model.events')));
test('crisp UI avoids backdrop blur',()=>{assert(!/backdrop-filter\s*:/.test(css));assert(css.includes('background:#0b3448')||css.includes('background:#0a3549'));assert(css.includes('background:#fff'))});
test('DepartmentOS records V46.13 Reporting capability',()=>{assert(dept.includes('Implementation checkpoint — V46.13'));assert(dept.includes('Reporting / structured-output capability'))});
test('Grounded contract keeps Personal Activity deterministic',()=>{assert(grounded.includes('V46.13 — Reporting / Portfolio Intelligence client'));assert(grounded.includes('not converted into an autonomous Grounded agent'))});
test('Activity45 module remains executable',()=>{const sandbox={module:{exports:{}},exports:{},globalThis:{}};vm.runInNewContext(activity,sandbox);assert.equal(typeof sandbox.module.exports.build,'function');assert.equal(typeof sandbox.module.exports.summarize,'function');assert.equal(typeof sandbox.module.exports.render,'function')});
let passed=0; for(const [n,fn] of checks){try{fn();console.log('PASS',n);passed++}catch(e){console.error('FAIL',n);throw e}}console.log(`${passed} V46.13 Portfolio Intelligence checks passed.`);
