const fs=require('fs'),vm=require('vm'),assert=require('assert');
const html=fs.readFileSync('index.html','utf8');
const app=fs.readFileSync('app.js','utf8');
const activity=fs.readFileSync('activity45.js','utf8');
const css=fs.readFileSync('activity45-ui.css','utf8');
const style=fs.readFileSync('style.css','utf8');
const dept=fs.readFileSync('DepartmentOS_Architecture.md','utf8');
const grounded=fs.readFileSync('GROUNDED-ARCHITECTURE.md','utf8');
const checks=[]; const test=(n,fn)=>checks.push([n,fn]);
function loadActivity(){const sandbox={module:{exports:{}},exports:{},globalThis:{},Date,Intl,Map,Set};vm.runInNewContext(activity,sandbox);return sandbox.module.exports}
const A=loadActivity();

test('V46.14 cache and visible build markers',()=>{assert(html.includes('neumDesk · V46.14'));assert(html.includes('activity45-ui.css?v=46.14'));assert(html.includes('activity45.js?v=46.14'));assert(html.includes('app.js?v=46.14-grounded-presentation-convergence'));assert(html.includes('style.css?v=46.14-grounded-presentation-convergence'))});
test('A full-screen workspace shell replaces export-first composition',()=>{assert(html.includes('activity45-workspace-shell'));assert(css.includes('width:100vw;height:100dvh'));assert(html.includes('Activity scope'));assert(html.includes('Portfolio Intelligence'))});
test('A period presets include month previous three-month ytd custom',()=>['This month','Previous month','Last 3 months','Year to date','Custom'].forEach(x=>assert(app.includes(x))));
test('A scope uses compact semantic areas',()=>['On-call','Rotations','Research','Innovation','Programme roles'].forEach(x=>assert(html.includes(x))));
test('B deterministic narrative helper is part of model summary',()=>{assert.equal(typeof A.narrative,'function');assert(activity.includes('summary.narrative=narrative(m)'));assert(html.includes('activity45.summary?.narrative'))});
test('B overview separates dated record and professional portfolio',()=>{assert(html.includes('Recorded in this period'));assert(html.includes('Dated activity only'));assert(html.includes('Professional portfolio'));assert(html.includes('Explicit relationships'))});
test('C timeline groups events by month',()=>{assert.equal(typeof A.timelineGroups,'function');const g=A.timelineGroups({events:[{start:'2026-09-01',kind:'oncall'},{start:'2026-10-02',kind:'rotation'}]});assert.equal(g.length,2);assert.equal(g[0].key,'2026-09');assert.equal(g[1].key,'2026-10');assert(html.includes('activity45TimelineGroups()'))});
test('D model keeps resident assignment and supervision distinct',()=>{assert(activity.includes('residentAssignments:[]'));assert(activity.includes('supervision:[]'));assert(html.includes('Resident assignments'));assert(html.includes('Residents supervised'))});
test('D formal supervision is rotation-derived not unit-attending inference',()=>{assert(activity.includes("same(r.supervising_attending_id,person.id)"));assert(activity.includes("role:'Formal resident supervisor'"));assert(!activity.includes('default supervisor'))});
test('E source match counts are model data',()=>{assert(activity.includes('matchCount:'));assert(html.includes('source.matchCount'));assert(html.includes('Open source ↗'))});
test('E unavailable source truthfulness remains explicit',()=>{assert(html.includes('cannot establish whether activity exists there'));assert(html.includes('never interpreted as zero activity'))});
test('F document is generated from same permission-scoped model',()=>{assert(app.includes('activity45.html=Activity45.render(model)'));assert(html.includes('Generated from the same permission-scoped snapshot'));assert(activity.includes('summary-copy'));assert(activity.includes('Resident assignments'));assert(activity.includes('Formal resident supervision'))});
test('F printable renderer uses deterministic narrative',()=>assert(activity.includes('(m.summary||summarize(m)).narrative')));
test('G staff entry auto-builds contextual snapshot',()=>assert(app.includes("if(personId && activity45.people.some(p=>Activity45.same(p.id,personId))) await activity45Generate()")));
test('G Grounded handoff carries person period structured snapshot',()=>{['activityStart:model.start','activityEnd:model.end','activitySnapshot:{generatedAt:model.generatedAt','summary:{...summary}'].forEach(x=>assert(app.includes(x)));assert(html.includes('Ask Grounded about this view'))});
test('G source navigation maps reporting evidence back to modules',()=>{assert(app.includes("oncall:'oncall_schedule'"));assert(app.includes("rotations:'resident_rotations'"));assert(app.includes("studies:'clinical_trials'"))});
test('H crisp visual system has no backdrop blur or glass haze',()=>{assert(!/backdrop-filter\s*:/.test(css));assert(css.includes('background:#0a3549'));assert(css.includes('background:#fff'));assert(css.includes('border-right:1px solid #dbe5e2'))});
test('H responsive workspace keeps mobile single-column behavior',()=>{assert(css.includes('@media(max-width:820px)'));assert(css.includes('.activity45-layout{display:block;overflow:auto}'))});
test('privacy boundary remains explicit',()=>{assert(html.includes('Private notes, contact details and leave reasons are excluded'));assert(activity.includes('contact details'))});
test('clinical unit label is user-facing Clinical units',()=>assert(activity.includes("label:'Clinical units'")));
test('DepartmentOS living ledger records hardened V46.14 honestly',()=>{assert(dept.includes('Architecture v1.8 · Implementation checkpoint: V46.14 hardening') || dept.includes('Architecture v1.9 · Implementation checkpoint: V46.14 presentation convergence'));assert(dept.includes('A → H implemented and hardened in this checkpoint'));assert(dept.includes('unknown source state is distinct from a known zero'));assert(dept.includes('transitional application overlay'))});
test('Grounded architecture records semantic reporting READ capability honestly',()=>{assert(grounded.includes('V46.14 hardening — Reporting READ capability'));assert(grounded.includes('reporting.personal_activity_snapshot'));assert(grounded.includes('Universal intent routing remains staged'))});
test('Activity45 build remains executable with rich summary helpers',()=>{assert.equal(typeof A.build,'function');assert.equal(typeof A.summarize,'function');assert.equal(typeof A.render,'function')});
test('R1 unknown is not rendered as zero',()=>{const sources={staff:{state:'ready',rows:[{id:'p',full_name:'P',staff_type:'attending'}]},oncall:{state:'unavailable',rows:[]},rotations:{state:'ready',rows:[]},units:{state:'ready',rows:[]},studies:{state:'restricted',rows:[]},projects:{state:'ready',rows:[]},lines:{state:'ready',rows:[]}};const m=A.build(sources.staff.rows[0],'2026-09-01','2026-09-30',sources,{oncall:true,rotations:true,studies:true,projects:true,lines:true});assert.equal(m.summary.metrics.oncall.state,'unknown');assert.equal(m.summary.metrics.oncall.value,null);assert.equal(m.summary.metrics.studies.state,'unknown');assert.match(A.render(m),/Partial view/)});
test('R1 retrieval terminology replaces completeness claims',()=>{assert(html.includes('included sources retrieved'));assert(html.includes('Retrieval evidence'));assert(!html.includes('Verified snapshot'));assert(!html.includes('% source coverage'))});
test('R1 soft-terminated rotations are retrieved separately',()=>{assert(activity.includes("rotation_status=terminated_early"));assert(activity.includes('an explicit actual termination date is not stored'));assert(activity.includes('planned rotation span is not shown as completed activity'))});
test('R2 formal document has dedicated rotation relationship sections',()=>{assert(activity.includes('Resident assignments'));assert(activity.includes('Formal resident supervision'));assert(activity.includes("['Source','Retrieval state','Relevant records','Checked (UTC)']"))});
test('R3 record-level provenance actions exist',()=>{assert(html.includes('Open record ↗'));assert(app.includes('const activity45OpenRecord'));assert(app.includes("researchOps.openStudy"));assert(app.includes("rotationOps.viewRotationDetails"))});
test('R4 shared reporting capability is registered and used by workspace',()=>{assert(app.includes("name:'reporting.personal_activity_snapshot'"));assert(app.includes('Activity45.snapshot'));assert(app.includes("groundedInvokeTool('reporting.personal_activity_snapshot'"))});
test('R4 Grounded handoff includes bounded metadata and full reporting dimensions',()=>{assert(app.includes('residentAssignments:pack'));assert(app.includes('issues:[...(model.issues||[])]'));assert(app.includes('truncated:(rows||[]).length>limit'));assert(app.includes('checkedAt:x.checkedAt'));assert(app.includes('research involvement ${period}'))});
test('R5 changed scope retains last completed snapshot',()=>{assert(app.includes("activity45.dirty=!!activity45.model"));assert(!app.includes("activity45.model=null; activity45.summary=null; activity45.html=''; activity45.error=''; activity45.view='overview'"));assert(html.includes('The workspace still shows the previous completed snapshot'))});
test('R5 searchable staff filtering exists',()=>{assert(html.includes('Search name or role'));assert(app.includes('activity45FilteredPeople'));assert(html.includes('activity45FilteredPeople()'))});
test('R6 tabs expose semantic accessibility state',()=>{assert(html.includes('role="tablist"'));assert(html.includes('role="tab"'));assert(html.includes(':aria-selected="activity45.view===tab.id"'));assert(html.includes('role="tabpanel"'));assert(app.includes("ev.key==='ArrowLeft'||ev.key==='ArrowRight'"))});
test('R6 mobile keeps Grounded reachable',()=>{assert(css.includes('.activity45-grounded{display:inline-flex'));assert(css.includes(".activity45-grounded::before{content:'G'"))});
test('R6 meaningful live-workspace type has 11px floor overrides',()=>{assert(css.includes('11px is the minimum for meaningful supporting information'));assert(css.includes('.activity45-kind,.activity45-evidence-summary span'))});
test('R7 architecture keeps live-browser validation as next gate',()=>{assert(dept.includes('live authenticated browser'));assert(dept.includes('print/PDF review') || dept.includes('print validation'));assert(dept.includes('Do not move to operational UI consistency until the live browser confirms'))});
test('period and relationship semantics survive a synthetic build',()=>{
 const sources={staff:{state:'ready',rows:[{id:'r1',full_name:'Resident One',staff_type:'resident'},{id:'a1',full_name:'Attending One',staff_type:'attending'}]},oncall:{state:'ready',rows:[]},rotations:{state:'ready',rows:[{id:'rot1',resident_id:'r1',supervising_attending_id:'a1',training_unit_id:'u1',start_date:'2026-09-01',end_date:'2026-09-30',rotation_status:'active'}]},units:{state:'ready',rows:[{id:'u1',unit_name:'Severe Asthma'}]},studies:{state:'ready',rows:[]},projects:{state:'ready',rows:[]},lines:{state:'ready',rows:[]}};
 const m=A.build(sources.staff.rows[0],'2026-09-01','2026-09-30',sources,{oncall:true,rotations:true,studies:true,projects:true,lines:true});
 assert.equal(m.residentAssignments.length,1);assert.equal(m.supervision.length,0);assert.equal(m.summary.residentRotations,1);assert.equal(m.sources.find(x=>x.key==='rotations').matchCount,1);
 const ms=A.build(sources.staff.rows[1],'2026-09-01','2026-09-30',sources,{oncall:true,rotations:true,studies:true,projects:true,lines:true});assert.equal(ms.supervision.length,1);assert.equal(ms.supervision[0].resident,'Resident One');
});

test('C1 broad leave follow-up widens person scope but inherits date',()=>{assert(app.includes("const broadPersonScope = /\\b(anyone|anybody|everyone"));assert(app.includes("kind:'leave_on_date'"));assert(app.includes("reviewScope:`All staff · ${label}`"));assert(app.includes("followupKind: 'leave_on_date', date: up[0]?.duty_date"))});
test('C2 typed broad leave language reaches the broad follow-up resolver before generic intent routing',()=>{assert(app.includes('const hasBroadPersonScope = /\\b(anyone|anybody|everyone'));assert(app.includes("if (hasBroadPersonScope && /(leave|absent|off|vacation|baja|ausen)/.test(q)) followup = askBarResolveFollowup(asked)"))});
test('C3 pinned context is labelled separately from current answer scope',()=>{assert(app.includes("label:pinned?'Pinned person':'Current reference'"));assert(html.includes('{{ askBarContextCard.label }}'));assert(html.includes('askBarClearPinnedContext()'));assert(app.includes("reviewScope:'Department-wide · Clinical Units'"));assert(app.includes("reviewScope: dayLabel ? `On-call schedule · ${dayLabel}`"))});
test('C4 structured answer detail is open by default when needed',()=>{assert(app.includes("['roster','profile','reslist','absence','board','research_brief'].includes(turn.visual.type)"));assert(html.includes("turn.reviewOpen ? 'Hide detail' : 'Show details'"))});
test('C5 units-by-specialty never interpolates an unresolved specialty',()=>{assert(app.includes("if (!kw)"));assert(app.includes("Unspecified specialty"));assert(app.includes('recorded across ${Object.keys(byspec).length} specialty group'))});
test('C6 staff cards use evidence-specific status and operational actions',()=>{assert(app.includes('No recorded absence today'));assert(html.includes('askbar-profile-record-btn'));assert(html.includes('Open record'));assert(html.includes("turn.profileDeep ? 'Less detail' : 'Details'"))});
test('C7 latest-answer affordance appears only after scrolling away',()=>{assert(html.includes('askBar.showLatest && askBar.turns.length'));assert(html.includes('@scroll.passive="askBarOnConversationScroll"'));assert(app.includes('askBar.showLatest = (c.scrollHeight - c.scrollTop - c.clientHeight) > 180'))});
test('C8 Grounded review timestamp is user-readable',()=>{assert(app.includes('askBarFormatSnapshotTime'));assert(html.includes("'Retrieved ' + askBarFormatSnapshotTime(turn.snapshotAt)"))});
test('C9 selected-period rotation collections are the single narrative and metric truth',()=>{
 const sources={staff:{state:'ready',rows:[{id:'r',full_name:'Ana',staff_type:'resident'}]},oncall:{state:'ready',rows:[]},rotations:{state:'ready',rows:[{id:'old',resident_id:'r',training_unit_id:'u',start_date:'2026-08-01',end_date:'2026-08-31',rotation_status:'completed'}]},units:{state:'ready',rows:[{id:'u',unit_name:'Unit'}]},studies:{state:'ready',rows:[]},projects:{state:'ready',rows:[]},lines:{state:'ready',rows:[]}};
 const m=A.build(sources.staff.rows[0],'2026-09-01','2026-09-30',sources,{oncall:true,rotations:true,studies:true,projects:true,lines:true});assert.equal(m.residentAssignments.length,0);assert.equal(m.summary.residentRotations,0);assert.match(m.summary.narrative,/No resident or supervision rotation overlaps/);
});
test('C10 professional portfolio count excludes time-bounded training relationships',()=>{
 const sources={staff:{state:'ready',rows:[{id:'r',full_name:'Ana',staff_type:'resident'}]},oncall:{state:'ready',rows:[]},rotations:{state:'ready',rows:[{id:'rot',resident_id:'r',training_unit_id:'u',start_date:'2026-09-01',end_date:'2026-09-30',rotation_status:'active'}]},units:{state:'ready',rows:[{id:'u',unit_name:'Unit'}]},studies:{state:'ready',rows:[]},projects:{state:'ready',rows:[]},lines:{state:'ready',rows:[]}};
 const m=A.build(sources.staff.rows[0],'2026-09-01','2026-09-30',sources,{oncall:true,rotations:true,studies:true,projects:true,lines:true});assert.equal(m.summary.trainingRelationships,1);assert.equal(m.summary.professionalPortfolioRelationships,0);assert.equal(m.summary.metrics.portfolioRelationships.value,0);assert(html.includes('professional portfolio relationships'));
});
test('C11 complete retrieval is not repeated as an overview status card',()=>{assert(!html.includes('class="activity45-status"'));assert(html.includes("['coverage'"));assert(html.includes('Evidence & interpretation'))});


test('P1 Grounded header stays compact while object context lives in the context bar',()=>{assert(html.includes('<span>Department intelligence</span>'));assert(!html.includes("askBarContextCard.label + ' in context'"));assert(style.includes('max-width:150px'))});
test('P2 simple facts are visually unboxed and evidence remains subordinate',()=>{assert(style.includes('Simple factual answers should read like answers'));assert(style.includes('.askbar-turn--fact .askbar-a-card'));assert(style.includes('background:transparent'));assert(style.includes('.askbar-turn--fact .askbar-trust'))});
test('P3 portfolio handoff renders as a compact context event',()=>{assert(app.includes('contextEvent:true'));assert(app.includes("eyebrow:'Portfolio context loaded'"));assert(html.includes('askbar-context-event'));assert(style.includes('Context changes are events, not assistant essays'))});
test('P4 broad leave answer uses resolved date label rather than the user question text',()=>{assert(app.includes("const label = dateIso===endIso ? Utils.formatDateShort(dateIso)"));assert(!app.includes("const label = fu.label || (dateIso===endIso"))});
test('P5 person cards are compact until Details is requested',()=>{assert(html.includes('askbar-profile-glance'));assert(html.includes("(turn.visual.profile.kind||'staff')==='staff' && turn.profileDeep"));assert(html.includes("turn.visual.profile.links.slice(0,1)"));assert(html.includes("turn.profileDeep && turn.visual.profile.missing.length"))});
test('P6 latest answer control is compact and only appears when scroll state requires it',()=>{assert(html.includes('>↓ Latest</button>'));assert(style.includes('border-radius:999px'));assert(app.includes('askBar.showLatest = (c.scrollHeight - c.scrollTop - c.clientHeight) > 180'))});
test('P7 structured review calls answer scope not review scope and profiles do not duplicate it',()=>{assert(html.includes('<span>Answer scope</span>'));assert(html.includes("turn.visual.type !== 'profile'"));assert(html.includes("turn.reviewOpen ? 'Hide detail' : 'Show details'"))});

let passed=0;for(const [n,fn] of checks){try{fn();console.log('PASS',n);passed++}catch(e){console.error('FAIL',n);throw e}}console.log(`${passed} V46.14 Personal Activity A-H checks passed.`);
