/* Shared, read-only presentation of the existing operational decision contract. */
(function(root){'use strict';
const labels={staff:'Staff',units:'Units',rotations:'Rotations',leave:'Leave',oncall:'On-call'};
function rows(f={}){const e=f.evidence||{};const list=Array.isArray(e.records)?e.records:Array.isArray(e.overlappingAssignments)?e.overlappingAssignments:[];
 const out=list.map((r,i)=>({key:String(r.id||i),label:r.unitName||r.role||'Related record',date:r.date||[r.start,r.end].filter(Boolean).join(' → '),id:r.id||'',detail:[r.status,r.reason].filter(Boolean).join(' · ')}));
 if(!out.length&&(e.conflictId||e.recordId))out.push({key:String(e.conflictId||e.recordId),id:e.conflictId||e.recordId,label:e.unitName||'Conflicting record',date:[e.start,e.end].filter(Boolean).join(' → '),detail:e.status||''});
 if(!out.length&&Array.isArray(e.dates))e.dates.forEach((d,i)=>out.push({key:'date'+i,label:'Recorded duty',date:d}));
 if(Array.isArray(e.periods))e.periods.forEach((r,i)=>out.push({key:'period'+i,label:'Capacity window',date:[r.start,r.end].filter(Boolean).join(' → ')}));
 return out;
}
function statusComponent({Vue}){return{props:{review:Object,source:String,checking:Boolean,error:String},setup(p){return{sources:Vue.computed(()=>Object.entries(p.review?.sourceState||{}).map(([key,value])=>({label:labels[key]||key,value:typeof value==='string'?value:'reported by server'}))) }},template:`<section class="workflow7-status" aria-live="polite"><strong>{{checking?'Checking current proposal':source==='server'?'Server review received':review?'Local preview · not server verified':'Complete the required fields to review'}}</strong><p v-if="review&&source!=='server'">Uses records available in this session. Missing or restricted sources can leave conflicts undetected. Saving requires another server check.</p><p v-else-if="source==='server'">Applies to the proposal reviewed. The server checks again when you save.</p><div v-if="source!=='server'&&sources.length" class="workflow7-sources"><span v-for="s in sources" :key="s.label">{{s.label}} · {{s.value==='ready'||s.value==='loaded'?'loaded':s.value}}</span></div><p class="workflow7-legend">Block: must resolve · Warning: review exception requirements · Advisory/context: information to consider</p></section>`}}
function evidenceComponent({Vue}){return{props:{finding:Object,can:Function},emits:['navigate'],setup(p){return{target:r=>({open_record:'resident_rotations',open_leave:'staff_absence',review_oncall:'oncall_schedule',review_rotations:'resident_rotations',review_capacity:'training_units'})[r.kind],records:Vue.computed(()=>rows(p.finding))}},template:`<details v-if="records.length || finding.resolutions?.length" class="workflow7-evidence"><summary>Review related details<span v-if="records.length"> · {{records.length}}</span></summary><p>Inspect the review evidence here while keeping your draft open.</p><ul v-if="records.length"><li v-for="r in records" :key="r.key"><strong>{{r.label}}</strong><span>{{r.date}}</span><small v-if="r.detail">{{r.detail}}</small><small v-if="r.id">Record {{r.id}}</small></li></ul><div v-if="finding.resolutions?.length"><strong>Suggested next steps</strong><ul><li v-for="(r,i) in finding.resolutions" :key="i">{{r.label}}<button v-if="target(r) && can(target(r),'read')" type="button" @click="$emit('navigate',{view:target(r),recordId:r.recordId||finding.evidence?.conflictId||finding.evidence?.recordId||null,label:r.label})">Open module →</button></li></ul></div></details>`}}
const api={rows,statusComponent,evidenceComponent};root.Workflow7=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
